ALTER TABLE companies ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS smtp_port INTEGER DEFAULT 587;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS smtp_user VARCHAR(255);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS smtp_password VARCHAR(255);
